apiVersion: apps/v1
kind: Deployment
metadata:
  name: blob-app
  labels:
    azure.workload.identity/use: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blob-app
  template:
    metadata:
      labels:
        app: blob-app
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: storage-sa
      containers:
        - name: app
          image: anuroopmgsq/python-azure-storage:v1
          env:
            - name: STORAGE_ACCOUNT
              value: "anurooppsa9uz"