replicaCount: 1

image:
  repository: anuroopmgsq.azurecr.io/python-azure-storage
  tag: latest

resources:
  requests:
    cpu: "1m"
    memory: "2Ki"
  limits:
    cpu: "5m"
    memory: "4Ki"

livenessProbe:
  httpGet:
    path: /
    port: 80

readinessProbe:
  httpGet:
    path: /
    port: 80